name: 'SCANOSS GH Action'
description: 'Scan your code from GH Workflow and take action based on detected components'
author: 'SCANOSS'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'target'
  color: 'purple'

# Define your inputs here.
inputs:
  github-token:
    description: 'Your GitHub token'
    required: true
  scanner-parameters:  
    description: 'Parameters to run a scan'
  output-path:
    description: 'Output result file name'
    required: false
    default: 'result.json'
  sbom-identify:
    description: 'Scan and identify components in SBOM file'
    required: false
  sbom-ignore:
    description: 'Ignore components specified in the SBOM file'
    required: false
  api-key:
    description: 'SCANOSS API Key token (optional - not required for default OSSKB URL)'
    required: false
  api-url:
    description: 'SCANOSS API URL (optional - default: https://osskb.org/api/scan/direct)'
    required: false

# Define your outputs here.
outputs:
  result-filepath:
    description: 'Scanner results filepath'
  output-command:
    description: 'Scanner command output'
    
runs:
  using: node20
  main: dist/index.js

