name: 'SCANOSS Code Scan Action'
description: 'Scan your code from GH Workflow and take action based on detected components'
author: 'SCANOSS'

branding:
  icon: 'check-circle'
  color: 'gray-dark'

inputs:
  policies:
    description: 'List of policies separated by comma (e.g., copyleft, undeclared)'
    required: false
  policies.halt_on_failure:
    description: 'Halt if a check fails'
    required: false
    default: true
  sbom.enabled:
    description: 'Enable SBOM Identify'
    required: false
    default: true
  sbom.filepath:
    description: 'SBOM filepath'
    required: false
    default: 'sbom.json'
  sbom.type:
    description: 'SBOM type (identify | ignore)'
    required: false
    default: 'identify'
  api.key:
    description: 'SCANOSS API Key token (optional - not required for default OSSKB URL)'
    required: false
  api.url:
    description: 'SCANOSS API URL (optional - default: https://osskb.org/api/scan/direct)'
    required: false
  dependencies.enabled:
    description: 'Scan dependencies (optional - default false)'
    required: false
    default: false
  dependencies.scope:
    description: 'Gets development or production dependencies (scopes - prod|dev)'
    required: false
    default: ''
  dependencies.scope.include:
    description: 'Custom list of dependency scopes to be included. Provide scopes as a comma-separated list.'
    required: false
    default: ''
  dependencies.scope.exclude:
    description: 'Custom list of dependency scopes to be excluded. Provide scopes as a comma-separated list.'
    required: false
    default: ''
  output.filepath:
    required: false
    default: 'results.json'
  github.token:
    description: 'Your GitHub token'
    required: false
    default: ${{ github.token }}
  licenses.copyleft.include:
    description: 'List of Copyleft licenses to append to the default list. Provide licenses as a comma-separated list.'
    required: false
  licenses.copyleft.exclude:
    description: 'List of Copyleft licenses to remove from default list. Provide licenses as a comma-separated list.'
    required: false
  licenses.copyleft.explicit:
    description: 'Explicit list of Copyleft licenses to consider. Provide licenses as a comma-separated list.'
    required: false


outputs:
  result-filepath:
    description: 'Scanner results filepath'
  stdout-scan-command:
    description: 'Scanner command output'
    
runs:
  using: node20
  main: dist/index.js

