name: 'SCANOSS Code Scan Action'
description: 'Scan your code from GH Workflow and take action based on detected components'
author: 'SCANOSS'

branding:
  icon: 'check-circle'
  color: 'gray-dark'

inputs:
  policies:
    description: 'List of policies separated by comma (e.g., copyleft, undeclared)'
    required: false
  policies.halt_on_failure:
    description: 'Halt if a check fails'
    required: false
    default: true
  api.key:
    description: 'SCANOSS API Key token (optional - not required for default OSSKB URL)'
    required: false
  api.url:
    description: 'SCANOSS API URL (optional - default: https://osskb.org/api/scan/direct)'
    required: false
  dependencies.enabled:
    description: 'Scan dependencies (optional - default false)'
    required: false
    default: false
  dependencies.scope:
    description: 'Gets development or production dependencies (scopes - prod|dev)'
    required: false
    default: ''
  dependencies.scope.include:
    description: 'Custom list of dependency scopes to be included. Provide scopes as a comma-separated list.'
    required: false
    default: ''
  dependencies.scope.exclude:
    description: 'Custom list of dependency scopes to be excluded. Provide scopes as a comma-separated list.'
    required: false
    default: ''
  output.filepath:
    required: false
    default: 'results.json'
  github.token:
    description: 'Your GitHub token'
    required: false
    default: ${{ github.token }}
  licenses.copyleft.include:
    description: 'List of Copyleft licenses to append to the default list. Provide licenses as a comma-separated list.'
    required: false
  licenses.copyleft.exclude:
    description: 'List of Copyleft licenses to remove from default list. Provide licenses as a comma-separated list.'
    required: false
  licenses.copyleft.explicit:
    description: 'Explicit list of Copyleft licenses to consider. Provide licenses as a comma-separated list.'
    required: false
  runtimeContainer:
    description: 'Specify runtime container to perform the scan.'
    default: 'ghcr.io/scanoss/scanoss-py:v1.19.0'
    required: false
  skipSnippets:
    description: 'Skip the generation of snippets.'
    default: false
    required: false
  scanFiles:
    description: 'Enable or disable file and snippet scanning.'
    default: true
    required: false
  scanossSettings:
    description: 'Settings file to use for scanning.'
    default: true
    required: false
  settingsFilepath:
    description: 'SCANOSS settings file path.'
    default: 'scanoss.json'
    required: false



outputs:
  result-filepath:
    description: 'Scanner results filepath'
  stdout-scan-command:
    description: 'Scanner command output'
    
runs:
  using: node20
  main: dist/index.js

