name: Test Action

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write
  checks: write 

jobs:
  test-action:
    name: GitHub Actions Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print output command
        run: echo "${{ steps.test-action.outputs.output-command }}"

      - name: Print Licenses
        run: echo "${{ steps.test-action.outputs.licenses }}"

      - name: Print Result
        run: cat "${{ steps.test-action.outputs.result-filepath }}"
