name: Test Action

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
#          sbom-ignore: 'scanoss-ignore.json'
           with-dependencies: true
#          github-token: ${{ secrets.GITHUB_TOKEN }}


      - name: Print stdout scan command
        run: echo "${{ steps.test-action.outputs.stdout-scan-command }}"

      - name: Print Results
        run: cat "${{ steps.test-action.outputs.result-filepath }}"
